# General, Vip y Staff son listas donde debes incluir las reglas en el siguiente formato:
# general:
# - 'Regla 1'

# reglas.general

# Para asignar un permiso a un conjunto de reglas, sigue el formato de reglas.rango:
# reglas:
#   general:
#   - 'Regla 1'
# En el caso anterior, el permiso debe ser reglas.general

reglas:
  general: # List String
    - "regla 1"
    - "regla 2"

